### ISSUE TITLE
work out flashing w/ genid.exe

### ISSUE THREAD

**Issue by mmoskal** [microsoft/jacdac-padauk#1]
my understanding is that we need to place genid.exe (attached) in the same folder as button.pdk compiled from button.prj with `RELEASE` defined. The writer should then find the exe and run it.

[genid.zip](https://github.com/microsoft/jacdac-padauk/files/6368570/genid.zip)

**Comment by jamesadevine** [comment]
Will try this today!

**Comment by jamesadevine** [comment]
Works well! Writer executes exe each time MCU is successfully programmed and removed
